---
deployment:
  tasks:
    - export DEPLOYPATH=/home/f4cw7dzgaokn/public_html
    - export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
    - cd /home/f4cw7dzgaokn/public_html && /usr/local/cpanel/3rdparty/bin/composer install --no-dev --optimize-autoloader --working-dir=/home/f4cw7dzgaokn/public_html
    - cd /home/f4cw7dzgaokn/public_html && /usr/local/bin/php8.3 artisan migrate --force
    - cd /home/f4cw7dzgaokn/public_html && /usr/local/bin/php8.3 artisan config:cache
    - cd /home/f4cw7dzgaokn/public_html && /usr/local/bin/php8.3 artisan route:cache
    - cd /home/f4cw7dzgaokn/public_html && /usr/local/bin/php8.3 artisan storage:link
